version: "3"
services:
    frontend:
        build: ./rag_fe
        ports:
            - 80:80
        volumes:
            - ./rag_fe/nginx.conf:/etc/nginx/conf.d/default.conf
    backend:
        build: ./rag_be
        ports:
            - 8080:8080
