apiVersion: apps/v1
kind: Deployment
metadata:
    name: rag-be-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: rag-be-pod
    template:
        metadata:
            labels:
                app: rag-be-pod
        spec:
            containers:
                - name: rag-be-container
                  image: ptatien/rag-be:latest
                  ports:
                      - name: pod-http
                        containerPort: 8080
                  env:
                      - name: GOOGLE_API_KEY
                        value: ""
                      - name: GROQ_API_KEY
                        value: ""
                      - name: NEO4J_URI
                        value: "neo4j+s://489814a4.databases.neo4j.io"
                      - name: NEO4J_USERNAME
                        value: "neo4j"
                      - name: NEO4J_PASSWORD
                        value: ""
