apiVersion: v1
kind: ConfigMap
metadata:
    name: frontend-configmap
data:
    nginx.conf: |
        server {
            listen       80;
            server_name  localhost;

            location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
              try_files $uri $uri/ /index.html;
            }


            location /api {
                proxy_pass http://rag-be-service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Optional settings to match your Vite config
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header Connection "";
                
                # Remove /api prefix when proxying
                rewrite ^/api/(.*)$ /$1 break;
            }
        }
